version: '3'

services:
  web:
    build: .
    command: /bin/bash setup_app.sh
    volumes:
      - .:/code
      - ./.env.docker:/code/.env
    depends_on:
      - db
      - redis
    links:
      - db
      - redis
    expose:
      - "8000:8000"
    networks:
      - app-net

  nginx:
    build: ./nginx
    ports:
      - 1337:80
    depends_on:
      - web
    networks:
      - app-net

  db:
    image: postgres:14-alpine
    restart: always
    ports:
      - 5432:5432
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgresql
    networks:
      - app-net

  redis:
    image: redis:6.0-alpine
    restart: always
    ports:
      - 6379:6379
    expose:
      - "6379:6379"
    networks:
      - app-net

networks:
  app-net:

volumes:
  redis_volume: